# Generated by Django 4.0.5 on 2022-07-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_alter_solution_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_formt',
            field=models.TextField(default=' '),
        ),
    ]
