# Generated by Django 4.0.5 on 2022-07-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_problem_input_formt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='input_formt',
            new_name='input_format',
        ),
    ]
